/*
  This file is generated by Emacs.
*/
import "../css/index.css";
import Vue from "vue";

import Resume from "../view/Resume.vue";

try {
    var Data = require("./data");
} catch (e) {
    var Data = {
        lhsData: [
            {
                title: 'Example Title 1',
                content: 'Example content 1'
            },
            {
                title: 'Example Title 2',
                content: 'Example content 2'
            }
        ],
        rhsData: [
            {
                title: 'Example Title 3',
                content: 'Example content 3'
            },
            {
                title: 'Example Title 4',
                content: 'Example content 4'
            }
        ]
    };
}

var app = new Vue(
    {
        el: "#app",
        template: `
        <Resume :lhsData="lhsData" :rhsData="rhsData"></Resume>`,
        components: {
            Resume
        },
        data: {
            lhsData: [],
            rhsData: []
        }
    }
);

app.lhsData = Data.lhsData;
app.rhsData = Data.rhsData;
