/*
  This file is generated by Emacs.
*/
import "../css/index.css";
import Vue from "vue";

import Resume from "../view/Resume.vue";

let Data;

try {
    Data = require("./data");
} catch (e) {
    Data = {
        lhsData: [],
        rhsData: []
    };
}

new Vue(
    {
        el: "#app",
        template: `
        <Resume :lhsData="lhsData" :rhsData="rhsData"></Resume>`,
        components: {
            Resume
        },
        data: {
            lhsData: Data.lhsData,
            rhsData: Data.rhsData
        }
    }
);
